### ISSUE TITLE
Check biome when in ocean and in other water areas such as a lake.

### ISSUE THREAD

**Issue by Layton1** [Dreamlinkh/Survival-Instincts#1]

**Comment by blinkhatri** [comment]
Not 100% sure but when I was above a lake it was labeled as an ocean, could be because it was either close to the actual ocean in my level or it may depend on the depth of the body of water.

When I went into the lake it was labeled as a lake.

The ocean was clearly labeled as an ocean biome.

Overall oceans are consistant and lakes may require more testing or a defined answer from a  wiki.

**Comment by Layton1** [comment]
Great; issue resolved for now.
